### ISSUE TITLE
Add a graphical footer to the website

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#104]
I would like to see a nicer footer on the website. Currently we only have a " probly powered by wordpress" on a white background. Some bedrock/lava texture that fades in from the top or similar would be great to have there.

**Comment by psiber-on-uncovery** [comment]
![bottom banner](https://cloud.githubusercontent.com/assets/16591000/12168417/14674436-b56d-11e5-916d-39636191bc06.png)

Are you fine with adding it to the banner etc?

**Comment by uncovery** [comment]
We can add it and look how it looks like of course

**Comment by psiber-on-uncovery** [comment]
Obviously it's intended to be tiled horizontally, just saying.

**Comment by uncovery** [comment]
done https://github.com/uncovery/uncovery_me/commit/8daf80bab605d806042c103265dcabbc73f0c924
