### ISSUE TITLE
Door & button etc usage on lots

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#109]
By default, lots should allow button & door usage. This does not seem to be the case always. 
Need to find out when exactly the issue occurs. Might be a default setting in worldguard.

**Comment by psiber-on-uncovery** [comment]
is there any way I can pull the pex permissions to check the permission nodes against worldguard etc?

**Comment by uncovery** [comment]
SELECT * FROM `region_flag` WHERE `flag` LIKE 'use' AND `value` LIKE 'deny' 
MySQL returned an empty result set (i.e. zero rows).

So there are no flags in the DB that restrict usage of buttons, doors etc

**Comment by uncovery** [comment]
PEX Permissions are not set on a by-lot base, this is done on the WG database

**Comment by psiber-on-uncovery** [comment]
if the region flags for world guard haven't specifically been denied it's likely higher up the hierarchy?

Are the default pex permission nodes available to view anywhere? Is it an inheritance issue with something not being explicitly allowed by default?

**Comment by uncovery** [comment]
ok, so there is a global region on every world in the worldguard permissions, which is set to allow for use in every world. So that cannot be it. Let me check the PEX for worldguard permissions just in case.

**Comment by uncovery** [comment]
No nothing. There is also modifyworld, but again, there is nothing I can find. I think we should first go back and try to reliably reproduce the issue and then try to find what is happening. Sleeping_owl brought this up, I will go back to him.

**Comment by psiber-on-uncovery** [comment]
Can't say I've ever had issues with doors / buttons / interactions on other users lots.

I've had issues with button doors causing issues for me due to high latency but that is about it.

**Comment by psiber-on-uncovery** [comment]
Yeah, understand the issue now. many kingdom lots experiencing the issue after being transferred post 1.8

Maybe the worldguard region isn't updating correctly on transfer? Will investigate the transfer code.

**Comment by uncovery** [comment]
More info from Sleeping_owl:
king_L12_A is a lot I acquired by dibs from Arielia when she went inactive.  Down at x:-6, y:15, z:11, is a pressure plate to launch a minecart.  Only permissioned players can utilize this.

Two lots south, king_J12_A is a lot that I purchased long ago version 1.3 or so.  There is a button to launch minecart at x:-9, y:16, z:540, that anyone permissioned or not is able to use.

The issue on king_L12_A only started after we moved to version 1.7 or 1.8, hard to tell because lot transfer seems to be key.  Before that anyone could launch a cart.

Another example is lot King_G21, Camerissan originally owned the lot and transferred it to her second account Treishalla recently.  Non-permissioned players cannot utilize the pressure plate at x:2180, y:16, z:1394, where they could before the lot was transferred to Treishalla.

Nearby button (x:2161, y:16, z:1348) on my lot that I have owned since 2013, non-permissioned players can utilize. 

I checked my notes and both examples had the lot transfers occur since we moved to version 1.8 on December 1, 2014.


On Friday, January 8, 2016 6:59 AM, Michael Littlefield <littlefieldm@yahoo.com> wrote:


Sure, king_L12_A is a lot I acquired by dibs from Arielia when she went inactive.  Down at x:-6, y:15, z:11, is a pressure plate to launch a minecart.  Only permissioned players can utilize this.

Two lots south, king_J12_A is a lot that I purchased long ago version 1.3 or so.  There is a button to launch minecart at x:-9, y:16, z:540, that anyone permissioned or not is able to use.

The issue on king_L12_A only started after we moved to version 1.7 or 1.8, hard to tell because lot transfer seems to be key.  Before that anyone could launch a cart.

**Comment by uncovery** [comment]
fixed it with new command. new lot transfers will be fine.
