### ISSUE TITLE
buyxp command removes levels at higher levels.

### ISSUE THREAD

**Issue by psiber-on-uncovery** [uncovery/uncovery_me#112]
above about level 20, buying xp causes a loss of experience.
going to test if this is default behaviour or something else.

> to reproduce:
   farm experience, preferably by natural methods up to level 25.
   run /buyxp 10
   level will go from 25 to 21 despite buying experience.

> not caused by the buyxp plugin code (checked recently)

**Comment by psiber-on-uncovery** [comment]
tested using my personal spigot server.

> default functionality of spigot is definitely working correctly at these levels to grant the correct amount of experience.

umc_ws_cmd("xp $xp $player", 'asConsole');

is the command which to my understanding basically just runs the native spigot command as though you had typed into the console window

xp 10 psiber

will investigate the umc_ws_cmd to see if there is something else at work here.

**Comment by uncovery** [comment]
Yeah in all other interactions, that's what umc_was_cmd does. There should be nothing else happening

**Comment by psiber-on-uncovery** [comment]
ok, open to ideas then?

anything active that you're aware of that would potentially change the default behaviour of the xp command at higher levels?

far as I can tell if the command works at all (even at lower levels) it shouldn't have different behaviour at higher levels.

it has not been remapped as an alias by another third party mod (like essentials does with some things ? )

**Comment by uncovery** [comment]
1) we need to level up the command to allow checking the XP (data is in $UMC_USER)
2) We need to check if the Essentials command is working better

**Comment by uncovery** [comment]
1) I reverted the XP ratio, it was correct. If you can buy 100XP with 10 Uncs it's FAR too much (it's equivalent of the XP you get from 100 mob kills). 0.1 ratio is good, fixed the docs maybe to make it clearer
2) I added a check to display the current XP level with /buyxp check. the XP number is in decimals (0.1...), we need to find out how to convert that into integers for proper dislay. once we know that, we can hopefully fix the issue. Otherwise maybe if we use the essentials command instead it might work better. We are currently using the built-in command.

**Comment by uncovery** [comment]
Tried to get some answers here: https://www.spigotmc.org/threads/essentials-xp-command-vs-built-in-xp.115030/

**Comment by psiber-on-uncovery** [comment]
at the revised ratio it would cost you
13950 uncs for level 30. 
why would anyone use this? It doesn't make sense.

best reference I have found for empirical values for experience brackets is
http://minecraft.gamepedia.com/Experience

tables under the leveling up subsection are great for empirical values for xp needed to get to levels and where you should be ending up.

I think we do need to discuss what level 30 is "worth" to buy, since the goal of the buyxp system is to provide a viable alternative to industrial scale mob farms which have their own sets of issues.

My thoughts is that if level 30 was more than 1500 uncs cost it's unlikely to see any usage. Especially since the new home / deposit / etc system will be drawing more uncs out.

**Comment by psiber-on-uncovery** [comment]
Guys over at https://www.spigotmc.org/threads/essentials-xp-command-vs-built-in-xp.115030/ aren't being much help at all.

They don't seem to understand that the experience is adding incorrectly, it doesn't have a scaling effect natively in spigot or essentials to my knowledge.

**Comment by uncovery** [comment]
This is the essentials code: https://github.com/essentials/Essentials/blob/d36d80933f8f672cd8bb0f210adc23aac10850ea/Essentials/src/com/earth2me/essentials/commands/Commandexp.java

**Comment by psiber-on-uncovery** [comment]
Hugely helpful.

Updated the command to specify give. should resolve ::crosses fingers::

**Comment by psiber-on-uncovery** [comment]
Fixed.

**Comment by uncovery** [comment]
yay!
