### ISSUE TITLE
Add pagination to item search results that return too many items

### ISSUE THREAD

**Issue by psiber-on-uncovery** [uncovery/uncovery_me#114]
item searches that return too many items should be capable of being narrowed down to list 50 items at a time to prevent the client parses crashing after being returned a list of 1444 items.

ie 
/search pot 1 
would return page 1 of results listing names 1-50
page 2 would return 51-100 etc

I will look into this tomorrow am, should be simple enough.

**Comment by psiber-on-uncovery** [comment]
done, pull request posted.

**Comment by uncovery** [comment]
merged it, please test it and tell me if it works now

**Comment by uncovery** [comment]
Also, please check your code when you write it, PHP needs ; at the end:

https://github.com/uncovery/uncovery_me/commit/97eb494bb36675568fa3cd5502e9ba79fef423c5

**Comment by psiber-on-uncovery** [comment]
noted with regard to the semicolons, just sloppy work on my part. won't happen again.

![capture](https://cloud.githubusercontent.com/assets/16591000/12228517/8ca8b80a-b877-11e5-946e-13bcaead8750.PNG)

Also, minor formatting issue to resolve with the paginated results, but otherwise working superbly.
