### ISSUE TITLE
Cast find queries to lowercase

### ISSUE THREAD

**Issue by psiber-on-uncovery** [uncovery/uncovery_me#115]
fix find queries so that
/find HORSE_EgG
will return a result for horse_egg

ie all searches /finds etc are treated as lowercase item name arguments.

**Comment by psiber-on-uncovery** [comment]
https://github.com/uncovery/uncovery_me/blob/master/websend_inc/shop.inc.php
line 299

**Comment by uncovery** [comment]
Wrong, https://github.com/uncovery/uncovery_me/blob/master/websend_inc/shop.inc.php#L723

**Comment by psiber-on-uncovery** [comment]
is that for the search pagination or the find query casing? isn't that for the search pagination?

**Comment by uncovery** [comment]
both. You referenced a different function (find).

**Comment by psiber-on-uncovery** [comment]
ah, you're right.

both functions should cast to lowercase. so if you search or find HorSe_EgG you will get the horse_egg result

**Comment by psiber-on-uncovery** [comment]
both done, pull request posted.

**Comment by uncovery** [comment]
merged it, please test

**Comment by psiber-on-uncovery** [comment]
working beautifully, search and finds now case non-specific
