### ISSUE TITLE
Update the github interface

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#120]
The Github interface was built during the time the server was not yet open-source.
Since this changed, we can link directly to github instead of having an own page for this stuff.

**Comment by psiber-on-uncovery** [comment]
ie instead of having development updates pushed on the website?

**Comment by uncovery** [comment]
well I wonder if we still have to have the github web page, if anyone can access the issues on github directly. We need to make a decision what we want to copy 1:1 to the website and what we have only on github.

**Comment by darthandrew1** [comment]
We should really just link directly to the Github in my opinion.

**Comment by darthandrew1** [comment]
Added with https://github.com/uncovery/uncovery_me/commit/8ffc44ab508a906312d5f29eec3f6307e8718adb, it adds direct links to the blog posts and status page.

**Comment by uncovery** [comment]
fixed.
