### ISSUE TITLE
Update voting links

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#124]
1) minecraftservers.org

already linked to the voting page

2) mineservers.net

current: http://www.mineservers.net/servers/834-uncovery-minecraft
Voting: http://www.mineservers.net/servers/834-uncovery-minecraft/vote

3) Minecraft-MP

current: http://minecraft-mp.com/server-s49
voting: http://minecraft-mp.com/server/49/vote/

4) minecraft-server-list.com

current: http://minecraft-server-list.com/server/54265/
voting: http://minecraft-server-list.com/server/54265/vote/

5) Minestatus.net

current: http://minestatus.net/152-uncovery-minecraft
voting: https://www.minestatus.net/152-uncovery-minecraft/vote

6) Planet Minecraft

current: http://www.planetminecraft.com/server/uncovery-minecraft/
voting: http://www.planetminecraft.com/server/uncovery-minecraft/vote/

7) minecraft-servers-list.org

current: http://www.minecraft-servers-list.org/details/uncovery/
voting: http://www.minecraft-servers-list.org/index.php?a=in&amp;u=uncovery

**Comment by psiber-on-uncovery** [comment]
Is this in https://github.com/uncovery/uncovery_me/blob/master/web.php somewhere? Or is this a seperate and displayed via wordpress somewhere?

**Comment by uncovery** [comment]
its separate

**Comment by uncovery** [comment]
done!
