### ISSUE TITLE
Cake Gives Hunger on Non-Permitted Lots, Doesn't decrease cake size

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#150]
https://youtu.be/hAJxxgHuOUA

**Comment by darthandrew1** [comment]
Update: Once you go to another world, your hunger resets. It may just be a visual bug.

**Comment by uncovery** [comment]
So I can close this, I assume?

**Comment by darthandrew1** [comment]
Yeah, not that big of a deal.
