### ISSUE TITLE
Fix /home command to avoid wrong-world destinations

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#152]
I have found a fork of essentials, where /tppos allows a world addon:
http://www.curse.com/bukkit-plugins/minecraft/essentialsx
Differences listed here: https://github.com/drtshock/Essentials/wiki

**Comment by psiber-on-uncovery** [comment]
hrmmm, almost there with the new /consoleTP plugin.

Would rather have the command made by ourselves than use a (supported?) fork of essentials.

Location(World world, double x, double y, double z, float yaw, float pitch)
Constructs a new Location with the given coordinates and direction

well advanced with sorting the new command.

**Comment by uncovery** [comment]
Of course we can have that. I will install the new version anyhow since its updated as opposed to the original.

**Comment by uncovery** [comment]
fixed!
