### ISSUE TITLE
Hunger games SQL issue

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#169]
I just got spammed with this here:

https://uncovery.net/websend/2016/01/24/06/Error_2016-01-24_06-24-53.5019260_5710707819089.html

**Comment by uncovery** [comment]
must be an error with umc_mysql_affected_rows($rst, true)

**Comment by uncovery** [comment]
Fixed!

**Comment by darthandrew1** [comment]
Hey, this is closed, but just a note. We cannot view that link because it requires a login.

**Comment by uncovery** [comment]
I know. These issues with those reports are more for myself as a reminder and bookmark instead of a request for help to others.
