### ISSUE TITLE
inta damage 2 potion doesnt do damage at all

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#17]
Bug or feature

**Comment by darthandrew1** [comment]
There's not really any point in allowing insta damage potions. Nobody really uses them so this shouldn't be a problem. This is probably something to do with NCP though. We should switch to a better plugin.

**Comment by uncovery** [comment]
Not sure what plugin you are referring to?

**Comment by darthandrew1** [comment]
NoCheatPlus.

**Comment by uncovery** [comment]
oh right. if you find a better plugin let me know. The main issue with NCP is that each time they release a new upgrade (which is frequent), the plugin is unable to auto-upgrade the config (which is big) and we have never taken t he time to properly configure it with good tolerances.

**Comment by darthandrew1** [comment]
Most of the good ones cost money. But I am willing to upgrade our config. Send me the current one and then delete it to regenerate it. I'll copy stuff over and edit some stuff.

**Comment by uncovery** [comment]
I will close this issue since it's duplicate with the NCP tolerances. Let's discuss over there.
