### ISSUE TITLE
add homes on the 2D-map to the menu for fast scrolling

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#171]
The homes on the 2D map should behave just like the user icons for fast scrolling to the location

**Comment by darthandrew1** [comment]
Wasn't this already done? I see my homes on the map.

**Comment by uncovery** [comment]
on the map, but not on the top menu like the user icons.

**Comment by darthandrew1** [comment]
Ah, okay.

**Comment by uncovery** [comment]
The new homes system has to be implemented as well. The system right now still uses the legacy homes.

**Comment by uncovery** [comment]
done.
