### ISSUE TITLE
Unable to edit my profile

### ISSUE THREAD

**Issue by leizhao4** [uncovery/uncovery_me#175]
When trying to update my profile at http://uncovery.me/wp-admin/profile.php, I get this message: "ERROR: Please enter a nickname." But there isn't a nickname field.

A code search shows that the nickname field is removed by JavaScript.

```
  jQuery(document).ready(function( $ ){
    $("#nickname,#display_name").parent().parent().remove();
  });
```

**Comment by darthandrew1** [comment]
I can confirm this, happening with Firefox 43.0.4

**Comment by uncovery** [comment]
hmmm we need to find some other way to disable editing the nicename (since we get it from minecraft) without disabling the form to be submitted. Maybe we can convert the text input field into a hidden text form field.

**Comment by uncovery** [comment]
ok try again please I hope I fixed it.

**Comment by leizhao4** [comment]
It works now but seems like nickname editing is not disabled. Is that intended?

**Comment by uncovery** [comment]
thanks for the reply, fixed it now.
