### ISSUE TITLE
Rewrite Minecarts page (http://uncovery.me/server-features/minecarts-steering/)

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#196]

**Comment by uncovery** [comment]
Can you be more explicit please what is wrong with the current page? Otherwise I will need to close this.

**Comment by darthandrew1** [comment]
We don't use Minecart Mania Reloaded anymore.

**Comment by uncovery** [comment]
removed the reference to the plugin. We use our own plugin now. Please check if you still find other issue with the page.

**Comment by darthandrew1** [comment]
Ok, thanks. Should I close this?
