### ISSUE TITLE
depositing clay blocks returns clay balls

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#199]

**Comment by psiber-on-uncovery** [comment]
Issue appears to be that the JSON name for clay blocks and clay balls appears identical.

ie when we deposit clay blocks id 82, it actually recognises the name as 'Clay' id 337.

not sure how best to resolve, i have poked through the references to clay but don't quite understand where the raw data populating the data conversion arrays is sourced from.

**Comment by uncovery** [comment]
This is easy most likely. The issue is that there are 2 different name sets for the same thing, depending who you ask. We need to know:

- The item names according to the minecraft wiki for both
- the names that you get in the websend inventory for both
then we need to make sure that they are matched with the translation table https://github.com/uncovery/uncovery_me/blob/master/includes/item_data.inc.php#L3487 properly

**Comment by uncovery** [comment]
fixed.
