### ISSUE TITLE
Find out what is resetting the time to 0 every couple of minutes so it never gets dark

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#205]
./latest.log:[00:16:01] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[00:37:40] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[02:29:02] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[04:14:43] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[04:25:42] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[04:45:23] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[05:16:28] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[05:36:10] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[06:07:17] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[06:26:50] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[07:17:58] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[07:38:08] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[09:50:00] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[10:13:45] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[12:05:45] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[12:26:47] [Server thread/INFO]: CONSOLE issued server command: /time set 0
./latest.log:[12:57:53] [Server thread/INFO]: CONSOLE issued server command: /time set 0

This happens for all worlds since the command does not specify a world.
Happens since 2016-01-04-1, originally 2 times a day now much more frequently as seen above.
Cannot find the command anywhere in the PHP Code.

**Comment by darthandrew1** [comment]
This could be a daylight senor hooked up to a command block somewhere in some world.

**Comment by uncovery** [comment]
no it cannot
Reasons: It says "console issued command", not command block
There are no command blocks. I am the only one who can use them, and I never did so.

**Comment by darthandrew1** [comment]
I believe that command blocks run from CONSOLE and not their own name. But other than that I'm really not sure why this is happening. Is this a plugin that is doing this?

**Comment by uncovery** [comment]
Either a plugin or some code somewhere I cannot identify properly, I put a checkpoint into the PHP code in case it comes from there.

**Comment by darthandrew1** [comment]
Do we have a list of plugins that the server uses? I might be able to identify it with them.

**Comment by uncovery** [comment]
try /plugins

**Comment by uncovery** [comment]
seems it was the blookmoon plugin.

**Comment by psiber-on-uncovery** [comment]
is the version we use open source?

I can always have a poke at it to resolve.

**Comment by uncovery** [comment]
I was using the last official release. The open source version is now in place but crashes on start so it's not active right now.

**Comment by psiber-on-uncovery** [comment]
i have found several repositories for bloodmoon.

is this the correct one to patch up?
https://github.com/lumien231/Bloodmoon

**Comment by psiber-on-uncovery** [comment]
this seems more legit, can i get a confirmation please before proceeding to attempt to patch to latest spigot?
https://github.com/DeltaStrium/BloodMoon

**Comment by psiber-on-uncovery** [comment]
and then we have yet another version...

https://github.com/betterphp/BloodMoon
but this is the one linked to by 
http://dev.bukkit.org/bukkit-plugins/bloodmoon/#w-contributing

**Comment by psiber-on-uncovery** [comment]
https://github.com/Samistine/BloodMoon/releases
appears fully updated to 1.8 ?

**Comment by uncovery** [comment]
I think I am using this one. (https://github.com/Samistine/BloodMoon/releases)
I have to make sure again I use the correct one.

**Comment by psiber-on-uncovery** [comment]
thanks, I will download it in a bit and see if I can recreate the issue on my local server

**Comment by psiber-on-uncovery** [comment]
Unc, how did this go after you fired up the new version and changed that config file we discussed? Did this resolve the issue?

**Comment by uncovery** [comment]
Well today I saw the time set 0 again and I saw again it was in the config, so I removed it again. I guess when I installed the latest version it re-created the config.
But this time, it also said  "oped notch" and toggle downfall so we definitely located the source.
I removed the stuff again from the config, so now we won't get it again.
