### ISSUE TITLE
Cannot login to uncovery only.

### ISSUE THREAD

**Issue by psiber-on-uncovery** [uncovery/uncovery_me#206]
Issues with log in - 03/02/16 8:46 PM GMT +8

Failed to connect to the server
Authentication servers are down. Please try again later sorry!

All other servers in my list work.

https://help.mojang.com/ lists authentication servers as up and working.

Curious?

**Comment by psiber-on-uncovery** [comment]
logged into minecraft.net no issue at all.

yet go into profile for minecraft.net and:

ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.

Generated by cloudfront (CloudFront)
Request ID: 7TNAnSpM0oFVVqnxEZjkewz2tMsOEBfGWQgKso6XZt8vE_pD2I8g5Q==

So sounds like a bogus setting / server / backend somewhere.

**Comment by MissEntrails** [comment]
I was having this issue as well

**Comment by psiber-on-uncovery** [comment]
Thanks for letting us know. Issue reopened.

**Comment by MissEntrails** [comment]
No problem, and yeah still having it. I tried to log into another random server from the MCservers list and it was fine.

**Comment by MissEntrails** [comment]
Not sure if this helps, but just in case it does- I was able to log in about 6:30ish est this morning. A couple others were also online, I was on for a few minutes and logged off. Tried to log back in around maybe 7:20, 7:30ish and had the error. Whispermischief seemed to be online when I was trying to log in as well.

**Comment by psiber-on-uncovery** [comment]
i was also able to log in about 6:30am GMT +8

whispermischief was also online at the time i was unable to login, but has since gone offline and I am still having the issue. Low likelihood of correlation.

**Comment by psiber-on-uncovery** [comment]
just resolved, try now.

**Comment by MissEntrails** [comment]
*thumbs up*

**Comment by uncovery** [comment]
"Authentication servers" is a minecraft servers issue, not here.It can be that other servers work since there are MANY auth servers around.
