### ISSUE TITLE
/history does not work

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#208]
I personally don't know what /history did, but others are saying that it doesn't work.

**Comment by uncovery** [comment]
That command does not exist, that's why it does not work, I guess?

**Comment by kidcodiwise** [comment]
I recall awhile back having a "/history sell/buy" command. I figured you disabled it when the online shop manager launched.

**Comment by uncovery** [comment]
Yeah that sounds familiar, and the only place where we would have had a toplevel command anyhow.

**Comment by darthandrew1** [comment]
This command does exist, it pops something up in game.

**Comment by darthandrew1** [comment]
Cant take a pic at the moment, not on computer. But it does show something.

**Comment by uncovery** [comment]
That's possible, the command shortcut probably was not removed. It then links to a /shop command that is not there anymore and displays the /shop help.

**Comment by uncovery** [comment]
fixed.
