### ISSUE TITLE
1.9 Preparations

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#209]
Minecraft updates can be a big thing with the Spigot community. We need to make sure that everything is compatible with the new update. Here's a small change-list:

- Add new block and item ids/names to shop/deposit etc

- Add shulker spawn egg to shop

- Check plugins for updates/upgrade them by han

**Comment by uncovery** [comment]
Good point.

regarding the blocks, we need:

- The minecraft number ID 
- the item name
- stackable yes/no
- subtypes? (colors etc)
- the graphics icon from the wiki
essentially the data for the item_data.inc.php. Those we can fill already before the 1.9 launch as available.

**Comment by darthandrew1** [comment]
We'll need the new enchantments as well.

**Comment by uncovery** [comment]
ah yes. those go into the same file.

**Comment by uncovery** [comment]
Enchantments data: 
https://github.com/uncovery/uncovery_me/blob/master/includes/item_data.inc.php#L210
Sample item data:
https://github.com/uncovery/uncovery_me/blob/master/includes/item_data.inc.php#L245

**Comment by darthandrew1** [comment]
I'm working on getting a table with all of the new blocks, items, etc

**Comment by darthandrew1** [comment]
Just noticed this, these enchantments appear to be mixed: 
https://github.com/uncovery/uncovery_me/blob/master/includes/item_data.inc.php#L233

**Comment by uncovery** [comment]
thanks, fixed.

**Comment by uncovery** [comment]
Can you put that into an excel/google sheets table instead?

**Comment by darthandrew1** [comment]
Sure.

**Comment by darthandrew1** [comment]
Do you mind if I make it a publically available spreadsheet? It might make it easier for other developers

**Comment by darthandrew1** [comment]
Here it is: https://docs.google.com/spreadsheets/d/1oNXP3tND4GV0X7mtP8cxoJopTdlQIwMlRe3HsNBDqC8/edit?usp=sharing

**Comment by uncovery** [comment]
Thanks. Here are the types what were not in there yet. Some of the icons are still missing

https://github.com/uncovery/uncovery_me/commit/a5e33fe3e04a1780a4c5d7b02c183e5d52e10e41

**Comment by uncovery** [comment]
FYI in your excel the skull item_name is wrong, just in case you use that for anything else. the proper ID is skeletonskull / 397

**Comment by darthandrew1** [comment]
Ah, okay. I was using the actual block ID.

**Comment by uncovery** [comment]
We still need the missing icons.

**Comment by uncovery** [comment]
I'll close this here now.
I won't add the egg immediately anyhow and the plugins checks won't be handled here.
