### ISSUE TITLE
Get SSL for the website (HTTPS)

### ISSUE THREAD

**Issue by ghost** [uncovery/uncovery_me#211]
Just a thought. An added layer of protection.

**Comment by uncovery** [comment]
Yeah I am working on that in the background. I subscribed to letsencrypt.com, I just need to install the automated cert renewal and we are good to go.

**Comment by darthandrew1** [comment]
If you need help, let me know.

**Comment by uncovery** [comment]
I need an auto-update script for certificates that works on CentOS/Apache

**Comment by darthandrew1** [comment]
Maybe this will help? http://www.vcritical.com/2010/11/automating-ssl-certificate-deployments-for-hp-ilo/

**Comment by uncovery** [comment]
Sorry, I was not clear above. Let'sEncrypt is a free service that provides certs for 90 days. Then they have to be renewed: https://letsencrypt.org/

**Comment by darthandrew1** [comment]
Ah - Here's this: https://community.letsencrypt.org/t/help-us-test-renewal-with-letsencrypt-renew/10562

**Comment by uncovery** [comment]
Yeah rather here: https://letsencrypt.org/howitworks/#writing-your-own-renewal-script
I need to test this.

**Comment by darthandrew1** [comment]
Try this:

```
cd /root/letsencrypt
git remote update
service apache2 stop
./letsencrypt-auto certonly --standalone --keep-until-expiring -d
www.uncovery.me
```

**Comment by uncovery** [comment]
This installs it, I need something that only renews the certs

**Comment by uncovery** [comment]
This is the proper way to do it: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-centos-7
