### ISSUE TITLE
Jail to get out of darklands abuse?

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#213]
I have seen players in-game asking to be jailed to get out of darklands.
We need to check if that really works. We have to make sure that we do not prevent darklanders from being jailed. The Jail command should probably kill users before jailing them.

**Comment by darthandrew1** [comment]
I can test it with you, if you'd like.

**Comment by darthandrew1** [comment]
Just tried this with alley, it doesn't work. It teleports you straight back to the darklands once you're unjailed.

**Comment by uncovery** [comment]
ah ok, thanks.
