### ISSUE TITLE
Idea: Switch from custom plugin to TrainCarts

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#214]
https://www.spigotmc.org/resources/traincarts.8557/

It's a really good plugin that utilizes almost all of our current features, but comes with more. Linking carts, redstone signs, and we can add action blocks with this plugin:

https://www.spigotmc.org/resources/tc-actionblocks.8903/

and we can also add hanging rails with this plugin:

https://www.spigotmc.org/resources/tc-hangrail.10224/

If there are any plugins that need updating then I'll happily update them. I've used TrainCarts a lot and I **LOVE** it. It only requires [BKCommonLib](https://www.spigotmc.org/resources/updated-bkcommonlib.7716/) which is a small dependency

**Comment by uncovery** [comment]
I do not want to have the additional functions of this plugin. It goes too far away from Vanilla. Also, the current system works fine.
