### ISSUE TITLE
Upgrade Forums CSS

### ISSUE THREAD

**Issue by ghost** [uncovery/uncovery_me#217]
The forums CSS needs some modernizing.

**Comment by uncovery** [comment]
I agree it's not very nice. But it's also rather complex.
We are using BBPress as a plugin. If you can find some theme or other already made CSS it would be great.

**Comment by darthandrew1** [comment]
I'd be willing to edit it for you, just send me a link with the CSS and I'll tidy it up.

**Comment by uncovery** [comment]
https://bbpress.org/download/

**Comment by uncovery** [comment]
Please do not just edit the CSS. Make a proper Theme so it won't get overwritten when a new version of the plugin comes out. Follow this guide:

https://codex.bbpress.org/themes/theme-compatibility/step-by-step-guide-to-creating-a-custom-bbpress-theme/

**Comment by darthandrew1** [comment]
Ok. What theme are we currently using and what is the folder name?

**Comment by uncovery** [comment]
We are using the default theme. Which folder do you mean? If you do it on your PC, you can just save the subfolder (whatever it is on your PC) and zip it, send it to me. You do not need to know the folder structure on my side.

**Comment by darthandrew1** [comment]
I've found a website with a few good themes, actually. Try this one out:
http://bbshowcase.org/themes/bbGrunge.zip

**Comment by uncovery** [comment]
If there a link where I can look at it before installing it?

**Comment by darthandrew1** [comment]
bbshowcase.org/forums/view/available-themes

It's the third from the bottom.

**Comment by uncovery** [comment]
The themes there do not work with our version of bbpress:
"September 2011: 
Please note bbPress version 2 is not bbPress at all, it is now just a WordPress plugin that simply took the bbPress name. It is not supported on this website."

also, most themes are outdated and the authors gone. I also cannot find any instructions on how to install those themes.

**Comment by uncovery** [comment]
with the new forum software this is not needed anymore.

**Comment by relavis** [comment]
aw, my suggestion was finally closed </3
