### ISSUE TITLE
Remove Donator level

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#221]
See http://uncovery.me/2016/02/10/changes-to-the-donator-system/

**Comment by uncovery** [comment]
- Update website / documentation
- Change userlevels
- change all the rest of the code where donators are handled different from normal users.

**Comment by darthandrew1** [comment]
In my opinion, the people that have already donated should keep at least the + sign next to their name.

**Comment by darthandrew1** [comment]
http://uncovery.me/about-this-server/user-levels/ bottom of the page
http://uncovery.me/about-this-server/faq/?cat=userlevels question 24
http://uncovery.me/communication/cha/ mentions + and ++. If you need a new pic let me know.

**Comment by uncovery** [comment]
The user suffix ++ is tied to userlevels in PEX. While we could simulate it with individual Vanities, there is the fundamental issue why I want to remove those: I find it unreasonable that someone who donated 2 USD 5 years ago is called a donator still today.

**Comment by darthandrew1** [comment]
Alright.

**Comment by uncovery** [comment]
ok, all 3 webpages done. 

I need an email from your sisters account (in-game or normal email) for that. And please do not post this kind of stuff here.

**Comment by uncovery** [comment]
ok so we have no more donators. We now have to rename all the donatorPlus stuff into Donator stuff.
That might be a bit tricky.

**Comment by uncovery** [comment]
Done.
