### ISSUE TITLE
Twitter page hacked?

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#227]
"ayy lmao my man wassup @kanyewest" was tweeted by @uncoveryme

**Comment by uncovery** [comment]
Yeah, thanks, no idea where that came from. Re did all security settings.

**Comment by darthandrew1** [comment]
Maybe because [this file](https://github.com/uncovery/uncovery_me/blob/master/archive/tweet/dotweet.php) contains the username and password.

**Comment by uncovery** [comment]
Possible. Anyhow, pw is changed now.
