### ISSUE TITLE
BottleXP broken?

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#230]
Just got this report from Stephdeg:

Hello, I have the feeling that the bottlexp command gives out a lot more bottles that what is described in the text. It probably gives out more xp in the bottles than what is on the character, for the moment. I have just tried it with 36 xp on me and received.. 223 bottles. I will definitely not use those bottles, I will destroy them. Best regards, Steph

**Comment by psiber-on-uncovery** [comment]
I think stephdeg probably hasnt tried bulk using bottles, or realised that xp scales exponentially.

level 36 is orders of magnitude more than level 30.

36 	2202 	157
37 	2368 	166

level 36 is 2202 points, / 10 = 220 bottles.

functionality as intended.

see: http://minecraft.gamepedia.com/Experience
for reference tables of points.

As someone who regularly uses more xp bottles than I produce, getting to 36 via bottles is far more than 223 bottles.

**Comment by uncovery** [comment]
ok, re-enabled it
