### ISSUE TITLE
Reduce serverlist voting to the 2-3 most important lists.

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#245]
We have too many lists, we should focus on those that really matter.

**Comment by Relavis** [comment]
These three all use Votifier (I believe) and they would be our best bet.

- http://minecraftservers.org/vote/160828

- http://www.minecraft-servers-list.org/index.php?a=in&u=uncovery

- https://www.minestatus.net/152-uncovery-minecraft/vote

If we were to reduce the list, we should give 2 rolls for the jackpot.

**Comment by uncovery** [comment]
Done by making the main one giving more money than the others
