### ISSUE TITLE
Prevent special chars in /home names

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#249]
/home should filter the input to not contain any non-alphabet chars.

**Comment by psiber-on-uncovery** [comment]
what about numbers? Are we trying to remove ascii values only or just limit it to a-z and A-Z

**Comment by uncovery** [comment]
numbers, underscore and dashes should be fine. the issue is when people use quotes, spaces or unicode etc.

**Comment by psiber-on-uncovery** [comment]
uncovery:

> Sorry, but I feel it's not really user-friendly to change the name and use that. Frankly I'd rather reject the invalid names and tell the user that they should not use certain characters. Would you be able to do that instead?

Will have to rewrite a bit of code to do this. not sure that sanitising via reg expressions will give me a return value either. Might be able to compare a sanitised string to the raw input and unless they match fail it?
