### ISSUE TITLE
Create blacklist for store/deposit

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#253]
There are still some items that won't pass through the store without losing information due to missing meta-data. 
We should create a blacklist of those items and prevent them to be sold/deposited so that users don't lose their stuff. It seems that the bug in spigot takes too long to be fixed so we have to make a permanent code to at least prevent damage on this issue.

**Comment by uncovery** [comment]
Will solve this bug: https://github.com/uncovery/uncovery_me/issues/241

**Comment by psiber-on-uncovery** [comment]
Can you link the bug report on spigot?

**Comment by uncovery** [comment]
Websend just stopped being developed 2 weeks ago, there are not more issues on the Github repo, I have trouble finding it.

**Comment by psiber-on-uncovery** [comment]
Least he left the repository open source, means we can fix it when / as needed.

**Comment by uncovery** [comment]
ok will close this and create a new one for the error issues.
