### ISSUE TITLE
Mail Spams Old Messages?

### ISSUE THREAD

**Issue by ETcodehome** [uncovery/uncovery_me#256]
Recently sent a mail and got the following spam as a result:

![2017-02-24_15 56 40](https://cloud.githubusercontent.com/assets/16591000/23295183/2b50971e-faaa-11e6-972c-413fa31342a8.png)

Will have to look into what is reporting all these mails that are presumably, old messages.
Could be a bogus "read" flag.

**Comment by michelleasaurus** [comment]
This happened to me, when I sent a mail as well. 
I checked all my inboxes, and there is no old mail.

**Comment by uncovery** [comment]
Should be fixed now, please let me know if not.

**Comment by michelleasaurus** [comment]
tested. fixed.
