### ISSUE TITLE
new eggs to lottery

### ISSUE THREAD

**Issue by alleywig** [uncovery/uncovery_me#266]
The goal is to update new eggs to the lottery and leave comments on the lottery list as to what each value represents as the egg item.

Data ID's
[http://minecraft.gamepedia.com/Data_values/Entity_IDs](url)

ID list
[https://github.com/uncovery/uncovery_me/blob/master/includes/item_data.inc.php#L3329](url)

Lottery list
[https://github.com/uncovery/uncovery_me/blob/master/websend_inc/lottery.inc.php#L190](url)

**Comment by uncovery** [comment]
fixed, thanks!
