### ISSUE TITLE
Incorrect message after donating

### ISSUE THREAD

**Issue by BDecima** [uncovery/uncovery_me#296]
![screen shot 2017-08-21 at 11 12 10 pm](https://user-images.githubusercontent.com/1012338/29547105-31330470-86c6-11e7-99cb-5c28c134f32d.png)

After submitting a donation through PayPayl, you are redirected back to the thank you page.  This page says that it received your donation and also that there was a problem.

**Comment by uncovery** [comment]
Thanks, this is the same as https://github.com/uncovery/uncovery_me/issues/228

**Comment by BDecima** [comment]
Thanks.  I searched and hadn't come across that other ticket.
