### ISSUE TITLE
Master Edit rights in City

### ISSUE THREAD

**Issue by LukeBillington** [uncovery/uncovery_me#310]
Containers can't be opened in the city by Masters. A chest was accidentally broken with old books by some early members, but was discovered the books can't be returned to it.

**Comment by uncovery** [comment]
Thanks for reporting. Please do not report 2 independent item in one issue, rather make 2, I have to split it otherwise.

**Comment by SkyTechBytes** [comment]
Have they tried putting a hopper leading into the chest and dropping the items into the hopper? It seems to be a satisfactory workaround. 

![2018-02-19_12 32 42](https://user-images.githubusercontent.com/36645753/36396073-1a8c6e5c-1571-11e8-90b4-d9ef58375736.png)

**Comment by uncovery** [comment]
So it seems that Elders AND Masters don't have the right to access containers in the Elder area.

**Comment by uncovery** [comment]
Fixed it.
