### ISSUE TITLE
"Fatal Error" when viewing any webpage when logged into website

### ISSUE THREAD

**Issue by SkyTechBytes** [uncovery/uncovery_me#320]
When I logged into the website today, I was greeted by this message (I would've posted on the forum, but when I try to access any webpage on the website while logged in, this happens - hopefully this is just temporary?):

Fatal error: Uncaught Error: Call to undefined function umc_get_uuid_level() in /home/minecraft/server/bin/includes/wordpress.inc.php:60 Stack trace: #0 /home/minecraft/server/bin/core_include.php(107): umc_wp_get_vars() #1 /home/minecraft/server/bin/index_wp.php(47): umc_set_environment() #2 /home/minecraft/public_html/wp-content/themes/twentyeleven-child/header.php(14): include_once('/home/minecraft...') #3 /home/minecraft/public_html/wp-includes/template.php(688): require_once('/home/minecraft...') #4 /home/minecraft/public_html/wp-includes/template.php(647): load_template('/home/minecraft...', true) #5 /home/minecraft/public_html/wp-includes/general-template.php(41): locate_template(Array, true) #6 /home/minecraft/public_html/wp-content/themes/twentyeleven-child/index.php(14): get_header() #7 /home/minecraft/public_html/wp-includes/template-loader.php(74): include('/home/minecraft...') #8 /home/minecraft/public_html/wp-blog-header.php(19): require_once('/home/minecraft...') #9 /home/minecraft/public_html/index.php(17) in /home/minecraft/server/bin/includes/wordpress.inc.php on line 60

**Comment by uncovery** [comment]
Thanks fixed.
