### ISSUE TITLE
Certain items can't be searched through shop

### ISSUE THREAD

**Issue by stayen** [uncovery/uncovery_me#323]
Several items, such as anything "chorus", end rods, shulker shells/boxes can't be found using /search or /find commands; the "Goods" section of "Shop manager" on the site lists the amount on sale, but there's no obvious way to find corresponding shop Ids.

**Comment by LukeBillington** [comment]
Newer items do not seem to be listed in search, however you can use /find to for `chorus_flower`, `chorus_fruit`, `end_rod`, and `purple_shulker_box`. For 1.12, the default color of a shulker box is purple, others may have posted other colors though, so it is worth checking. In 1.13 purple shulker boxes will become a `minecraft:shulker_box` item, and there will be a new purple shulker box with a richer color that matches the purple of other dyed items.

**Comment by stayen** [comment]
Confirming, using /find with known items names work.

**Comment by uncovery** [comment]
We are using the internal text file from the essentialsX plugin for this: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/items.csv 

I am afraid that the file is not up to date. It even still uses item numbers instead of names.

**Comment by uncovery** [comment]
If we do not find an alternative text, the next best way would be to create a new search function ourselves that works better with wildcards. It's tricky though since there are MANY ways how to describe one thing without any wildcard matches between each other.

**Comment by uncovery** [comment]
actually I found a bug in the code. Please try again if you can do /search now

**Comment by stayen** [comment]
Confirming - /search now works.

**Comment by uncovery** [comment]
thanks, closed!
