### ISSUE TITLE
Erroneous enchantments displayed in the [broadcast] when items are purchased from the shop and obtained via the lottery

### ISSUE THREAD

**Issue by kzrnvd** [uncovery/uncovery_me#331]
Hi Unc,

It seems that enchantments displayed in the [broadcast] when items are purchased from the shop and obtained via the lottery are different than what is actually on the items. Just today, Riedi73 uploaded a diamond pickaxe with mending but when purchased, the [broadcast] stated that a diamond pickaxe with aqua affinity 1 was bought (even though the actual pickaxe does have the mending enchantment on it). In addition, I was supposed to have received a trident with channeling 1 from the lottery announcer but the actual enchantment on the trident was Loyalty 2 when withdrew from the repository. I have the screenshots if you required them.

Regards,

kzr_nvd

**Comment by uncovery** [comment]
thanks, this should work now
