### ISSUE TITLE
Better CSS for user profile pages

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#41]
The User pages have to be revamped completely. They should show off the user achievements and act as a showcase for this builds, his trading volume etc etc

**Comment by uncovery** [comment]
Done tabbed layout, still missing is a more compact way to display lots

**Comment by uncovery** [comment]
Done better layout for lots, still need to make sure that the bounding box stretches over the lots to the bottom.

**Comment by uncovery** [comment]
Also possibly limit forum posts to the last x years?

**Comment by darthandrew1** [comment]
Is this done?

**Comment by uncovery** [comment]
yeah I would say so.
