### ISSUE TITLE
Faulty item_names

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#59]
These can be anywhere, be it in the inventory of a person or past transaction records

6:11:21 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:11:21: Could not identify diamonds umc_goods_get_text
6:11:48 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:11:48: Could not identify snad umc_goods_get_text
6:13:37 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:13:37: Could not identify goldenapple umc_goods_get_text
6:13:44 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:13:44: Could not identify dirt1 umc_goods_get_text
6:14:26 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:14:26: 0.049939 sec
E_WARNING: Illegal string offset 'short' 
Source: Line 135 of file /home/minecraft/server/bin/plugin.php
Error Report: http://uncovery.net/websend/2015/06/17/00/Error_2015-06-17_00-14-26.6928930_8356386609375.html
6:16:28 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:16:28: Could not identify redglass umc_goods_get_text
6:16:41 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:16:41: Could not identify red umc_goods_get_text
6:16:52 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:16:51: Could not identify wood umc_goods_get_text
6:17:30 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:17:29: Could not identify goldenapples umc_goods_get_text
6:17:38 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:17:38: Could not identify golden umc_goods_get_text
6:18:06 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:18:06: Could not identify ocelot umc_goods_get_text
6:18:21 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:18:20: Could not identify ocelotegg umc_goods_get_text
6:18:38 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:18:38: Could not identify boots umc_goods_get_text
6:18:45 PM - server@spiesshofer.com: [Uncovery.me] 2015-06-17 00:18:45: Could not identify sword umc_goods_get_text

**Comment by psiber-on-uncovery** [comment]
Have added some additional debug output to the umc_goods_get_text function that should at least clarify if these are data values that are being fed in or jsut dodgy string names.

My thoughts is that they are legacy database entries that don't use the correct item_name to be resolved by UMC_DATA[item_name] or have incorrect casing such as in 
https://github.com/uncovery/uncovery_me/issues/71

I have added a casing check that should resolve the casing issue (easy) but these other items are something that is being pulled from old data that has been manually entered somewhere i think.

dirt1, snad, etc appear to be simple mispellings or extra characters, whilst the rest just appear to be insufficiently clearly defined data.

**Comment by psiber-on-uncovery** [comment]
Unfamiliarity with php here but is using

array debug_backtrace ([ int $options = DEBUG_BACKTRACE_PROVIDE_OBJECT [, int $limit = 1 ]] )

the correct way to find what function is calling umc_goods_get_text when the error is being cast?
or would something like

array_walk(debug_backtrace(),create_function('$a,$b','print "{$a[\'function\']}()(".basename($a[\'file\']).":{$a[\'line\']}); ";'));

be better for producing some human readable output?

**Comment by uncovery** [comment]
We have the XMPP_ERROR_trace to track that

**Comment by uncovery** [comment]
I will close this and potentially re-open for individual items or just directly fix them. I do not think there is a general valid fix for this issue unless we write some code that would traverse all the databases and logs and find invalid items.
