### ISSUE TITLE
replace openflashchart with non flash alternative

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#89]
We are running flash based visualization charts in the website, but flash is buggy and soon 2010. We need an alternative.

**Comment by uncovery** [comment]
Could be done for example with Google charts (https://developers.google.com/chart/interactive/docs/gallery/linechart) of highcharts (http://www.highcharts.com/)

**Comment by leizhao4** [comment]
AmCharts.js and D3.js are good too.

**Comment by uncovery** [comment]
I just realized we are using amCharts already in the shopmanager:
https://github.com/uncovery/uncovery_me/blob/master/shop_manager.php#L192

Donation charts need to be replaced: 
https://github.com/uncovery/uncovery_me/blob/master/donation.php#L309

**Comment by uncovery** [comment]
done!
