### ISSUE TITLE
Allow More "Lazy" Item Names

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#98]
ex: 
powered_rail => poweredrail
melon_slice => melonslice

**Comment by uncovery** [comment]
Currently, we allow easier names in the /search command to identify the proper, unique item name. Then the item name needs to be used for /find etc.

This request requires that the easier names can be used for all the other commands as well.
The easier names are stored in this file: https://github.com/uncovery/uncovery_me/blob/master/includes/item_search.inc.php

They come from an index file of the Essential plugin: https://github.com/essentials/Essentials/blob/2.x/Essentials/src/items.csv

**Comment by uncovery** [comment]
fixed with https://github.com/uncovery/uncovery_me/commit/fa581858ee23e75faf2ad6dfebd27fa9c478a0c3

Please note that this will only allow the pre-set names that are available in /search. No others yet. If we wanted to expand that list, we would have to start maintaining our own dictionary.
